[[redirects]]
from = "/alwaysrenderthis/"
to = "/.netlify/functions/alwaysrerender"
status = 200
force = true
_generated_by_eleventy_serverless = "alwaysrerender"

[[redirects]]
from = "/zip_url_js_sametwo/:url_zip/index.html"
to = "/.netlify/functions/firstrequestrender"
status = 200
force = true
_generated_by_eleventy_serverless = "firstrequestrender"

[[redirects]]
from = "/zip_url_js_sameone/:url_zip/index.html"
to = "/.netlify/functions/firstrequestrender"
status = 200
force = true
_generated_by_eleventy_serverless = "firstrequestrender"

[[redirects]]
from = "/zip_url_js_dynamic/:url_zip/index.html"
to = "/.netlify/functions/firstrequestrender"
status = 200
force = true
_generated_by_eleventy_serverless = "firstrequestrender"

[[redirects]]
from = "/buildfirstrequest/"
to = "/.netlify/functions/firstrequestrender"
status = 200
force = true
_generated_by_eleventy_serverless = "firstrequestrender"
